services:
  nat:
    image: nat-nim-handson:1.6.0
    env_file:
      - .env
    volumes:
      - ./workflow.yml:/app/workflows/workflow.yml:ro
    command:
      - 'run'
      - '--config_file'
      - '/app/workflows/workflow.yml'
      - '--input'
      - 'Who is the current CEO of NVIDIA, and what date is it today?'
